### ISSUE TITLE
Is 25 a hard limit or can we confirm even more with one API request to safe some zoho api requests?

### ISSUE THREAD

**Issue by tilman** [trieb-work/zoho-ts#13]
https://github.com/trieb-work/zoho-ts/blob/f86ffbdeb18566c6e130f8528d5f12fd5ccfb721/src/service/salesOrder.ts#L149

If it is a hard limit please close the issue otherwise I would suggest to increase it to at least 100 and make the option configurable via an optional argument like this:
```
public async confirm(ids: string[], chunkSize: number = 100): Promise<void> {
```

**Comment by tilman** [comment]
@JannikZed ?

**Comment by JannikZed** [comment]
API handles max 25 salesorders at once, that's why we created this chunk size :) 
25 is a hard limit.
