### ISSUE TITLE
TokenHost parameter

### ISSUE THREAD

**Issue by ghost** [trieb-work/zoho-ts#15]
Hello - great work on this. Need ability to set tokenHost on client.ts to change domain from .eu to .com just like can pass baseUrl.

**Comment by tilman** [comment]
Hello, not sure what you mean. Do you want to set tokenHost as a Header param? Feel free to create a PR with your changes and I'm happy to merge it.

**Comment by JannikZed** [comment]
@StreamSurfer added datacenter select via #17 - will be included in the next release. Test it out :)

**Comment by JannikZed** [comment]
released in 0.5.38

**Comment by ghost** [comment]
@JannikZed awesome, nice work!
