### ISSUE TITLE
Cant change API flavors

### ISSUE THREAD

**Issue by panrosk** [trieb-work/zoho-ts#20]
Cant change API flavors. Trying to use Books, connects to inventory

**Comment by JannikZed** [comment]
@panrosk can you provide the exact error? Can you try setting also the scope like to this: "ZohoBooks.fullaccess.all" - maybe it fails because the lib tries to create a token that is valid also for Zoho Inventory

**Comment by JannikZed** [comment]
@panrosk can you check this issue again? Furthermore, I pushed a new version, that is automatically selecting the token scope depending on the API flavor
